name: Update Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mcpb:
    name: Build MCPB Package
    needs:
      - release-draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Build MCPB
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:mcpb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: garoon-mcp-server.mcpb
          path: build/garoon-mcp-server.mcpb

  upload-binaries:
    name: Upload MCPB Package to Release Draft
    needs:
      - build-mcpb
      - release-draft
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Upload MCPB package
        run: |
          gh release upload ${{ needs.release-draft.outputs.tag_name }} ./artifacts/garoon-mcp-server.mcpb --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
